[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Save risk card stuff to here
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''G.culled_table =  recursive_table_cull{'''
position = 'before'
payload = '''
local risks = {}
if G.GAME.plsa_risks_active then
	for k, v in ipairs(G.GAME.plsa_risks_active) do
		if v and (type(v) == "table") and v.is and v:is(PLSA.RiskObject) then
			local ret = v:save()
			if ret then risks[k] = ret end
		end
	end
end

'''
match_indent = true

# Perpetuate logic
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''draw_card(G.hand, G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])'''
position = 'at'
payload = '''
if G.GAME.plsa_perpetuate then
	draw_card(G.hand, G.deck, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])
	G.deck:shuffle('plsa_perpetuate_shuf'..G.GAME.round_resets.ante)
else
	draw_card(G.hand, G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])
end
'''
match_indent = true

# Mini context for risk cards ONLY.
# context.plsa_risk_joker_moved
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''card.rank = k'''
position = 'before'
payload = '''
card.plsa_old_rank = card.rank
if k ~= card.plsa_old_rank and self == G.jokers then
	local effects = {}
	for _, risk in ipairs(G.GAME.plsa_risks_active or {}) do
		local r = risk:calculate({ plsa_risk_joker_moved = true })
		if r and type(r) == "table" then SMODS.merge_effects(effects, r) end
	end
	if next(effects) then
		SMODS.calculate_effect(effects, G.deck.cards[1])
	end
end
'''
match_indent = true
